# Generated by Django 2.0.7 on 2018-08-01 23:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('estaaweb', '0003_auto_20180802_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hair',
            name='image',
            field=models.ImageField(upload_to='estaaweb/templates/static/img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 23, 50, 3, 887514, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='estaaweb/templates/static/img'),
        ),
    ]
