# Generated by Django 2.0.7 on 2018-08-02 22:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('estaaweb', '0004_auto_20180802_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('image', models.ImageField(upload_to='estaaweb/templates/static/img')),
                ('product', models.ForeignKey(on_delete='cascade', to='estaaweb.Hair')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 2, 22, 3, 38, 677674, tzinfo=utc)),
        ),
    ]
