# Generated by Django 2.0.7 on 2018-08-05 17:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('estaaweb', '0007_auto_20180803_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hair',
            name='length',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 5, 17, 33, 41, 558073, tzinfo=utc)),
        ),
    ]
