# Generated by Django 2.0.7 on 2018-08-18 16:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('estaaweb', '0010_auto_20180818_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 18, 16, 23, 13, 544456, tzinfo=utc)),
        ),
    ]
